// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmidzecsvftiintpacdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtaWR6ZWNzdmZ0aWludHBhY2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjgyMzYsImV4cCI6MjA2NTUwNDIzNn0.GodFC007kLflYVvcbJ1qRTKwGkipG8emME25KgO_7Is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);